# Generated by Django 5.2.11 on 2026-02-27 00:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_phone', models.CharField(max_length=32)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('service_detail', models.CharField(blank=True, max_length=180)),
                ('billing_month', models.DateField(help_text='Guardar como primer día del mes (ej: 2026-02-01)')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-billing_month', 'client_name'],
            },
        ),
    ]
